// Mocks generated by Mockito 5.4.6 from annotations
// in coin_gecko_graduation_project_metorship/test/features/home/presentation/manager/home_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:coin_gecko_graduation_project_metorship/core/api/result.dart'
    as _i4;
import 'package:coin_gecko_graduation_project_metorship/features/home/data/models/global_data_model.dart'
    as _i5;
import 'package:coin_gecko_graduation_project_metorship/features/home/data/models/market_coin_model.dart'
    as _i8;
import 'package:coin_gecko_graduation_project_metorship/features/home/data/models/trending_coin_model.dart'
    as _i7;
import 'package:coin_gecko_graduation_project_metorship/features/home/data/repos/home_repo.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HomeRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepo extends _i1.Mock implements _i2.HomeRepo {
  MockHomeRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.GlobalDataModel>> getGlobalData() =>
      (super.noSuchMethod(
        Invocation.method(
          #getGlobalData,
          [],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.GlobalDataModel>>.value(
            _i6.dummyValue<_i4.Result<_i5.GlobalDataModel>>(
          this,
          Invocation.method(
            #getGlobalData,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.GlobalDataModel>>);

  @override
  _i3.Future<_i4.Result<_i7.TrendingData>> getTrendingCoins() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrendingCoins,
          [],
        ),
        returnValue: _i3.Future<_i4.Result<_i7.TrendingData>>.value(
            _i6.dummyValue<_i4.Result<_i7.TrendingData>>(
          this,
          Invocation.method(
            #getTrendingCoins,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i7.TrendingData>>);

  @override
  _i3.Future<_i4.Result<List<_i8.MarketCoinModel>>> getMarkets({
    String? vsCurrency = 'usd',
    String? order = 'market_cap_desc',
    int? perPage = 20,
    int? page = 1,
    bool? sparkline = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarkets,
          [],
          {
            #vsCurrency: vsCurrency,
            #order: order,
            #perPage: perPage,
            #page: page,
            #sparkline: sparkline,
          },
        ),
        returnValue: _i3.Future<_i4.Result<List<_i8.MarketCoinModel>>>.value(
            _i6.dummyValue<_i4.Result<List<_i8.MarketCoinModel>>>(
          this,
          Invocation.method(
            #getMarkets,
            [],
            {
              #vsCurrency: vsCurrency,
              #order: order,
              #perPage: perPage,
              #page: page,
              #sparkline: sparkline,
            },
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i8.MarketCoinModel>>>);
}
