// Mocks generated by Mockito 5.4.6 from annotations
// in coin_gecko_graduation_project_metorship/test/features/auth/data/repos/auth_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:coin_gecko_graduation_project_metorship/core/api/result.dart'
    as _i7;
import 'package:coin_gecko_graduation_project_metorship/features/auth/data/data_source/local/auth_local_data_source.dart'
    as _i6;
import 'package:coin_gecko_graduation_project_metorship/features/auth/data/data_source/remote/auth_remote_data_source.dart'
    as _i2;
import 'package:coin_gecko_graduation_project_metorship/features/auth/data/models/user_model.dart'
    as _i5;
import 'package:local_auth/local_auth.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i2.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> createUserWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUserWithEmailAndPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #createUserWithEmailAndPassword,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> saveUserData({required _i5.UserModel? userModel}) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserData,
          [],
          {#userModel: userModel},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #signIn,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i3.Future<String>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i6.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i7.Result<bool>> checkBiometricSupport() => (super.noSuchMethod(
        Invocation.method(
          #checkBiometricSupport,
          [],
        ),
        returnValue:
            _i3.Future<_i7.Result<bool>>.value(_i4.dummyValue<_i7.Result<bool>>(
          this,
          Invocation.method(
            #checkBiometricSupport,
            [],
          ),
        )),
      ) as _i3.Future<_i7.Result<bool>>);

  @override
  _i3.Future<_i7.Result<List<_i8.BiometricType>>> getAvailableBiometrics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableBiometrics,
          [],
        ),
        returnValue: _i3.Future<_i7.Result<List<_i8.BiometricType>>>.value(
            _i4.dummyValue<_i7.Result<List<_i8.BiometricType>>>(
          this,
          Invocation.method(
            #getAvailableBiometrics,
            [],
          ),
        )),
      ) as _i3.Future<_i7.Result<List<_i8.BiometricType>>>);

  @override
  _i3.Future<_i7.Result<bool>> authenticateBiometric(String? reason) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticateBiometric,
          [reason],
        ),
        returnValue:
            _i3.Future<_i7.Result<bool>>.value(_i4.dummyValue<_i7.Result<bool>>(
          this,
          Invocation.method(
            #authenticateBiometric,
            [reason],
          ),
        )),
      ) as _i3.Future<_i7.Result<bool>>);
}
