// Mocks generated by Mockito 5.4.6 from annotations
// in coin_gecko_graduation_project_metorship/test/features/portfolio/presentation/cubit/portfolio_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:coin_gecko_graduation_project_metorship/core/api/result.dart'
    as _i4;
import 'package:coin_gecko_graduation_project_metorship/features/portfolio/data/model/simple_price_model.dart'
    as _i5;
import 'package:coin_gecko_graduation_project_metorship/features/portfolio/data/repository/portfolio_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PortfolioRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPortfolioRepository extends _i1.Mock
    implements _i2.PortfolioRepository {
  MockPortfolioRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.SimplePriceModel>> getSimplePrice({
    required String? ids,
    required String? vsCurrencies,
    bool? includeChange,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSimplePrice,
          [],
          {
            #ids: ids,
            #vsCurrencies: vsCurrencies,
            #includeChange: includeChange,
          },
        ),
        returnValue: _i3.Future<_i4.Result<_i5.SimplePriceModel>>.value(
            _i6.dummyValue<_i4.Result<_i5.SimplePriceModel>>(
          this,
          Invocation.method(
            #getSimplePrice,
            [],
            {
              #ids: ids,
              #vsCurrencies: vsCurrencies,
              #includeChange: includeChange,
            },
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.SimplePriceModel>>);
}
